services:
  proxy:
    build: .
    environment:
      - SERVICE=proxy
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GPT_MODEL=${GPT_MODEL:-gpt-4-turbo}
      - MAX_TOKENS=${MAX_TOKENS:-500}
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 15s
    command: >
      bash -c "apt-get update && apt-get install -y curl && cd proxy && uvicorn main:app --host 0.0.0.0 --port 8000"

  streamlit:
    build: .
    environment:
      - SERVICE=streamlit
      - API_URL=http://proxy:8000
    ports:
      - "8501:8501"
    depends_on:
      proxy:
        condition: service_healthy 